sudo: required

services:
  - docker

env:
  global:
    - GIT_NAME: "Richard Chien"
    - GIT_EMAIL: richardchienthebest@gmail.com
    - DOCKER_USER: richardchien
    - DOCKER_EMAIL: richardchienthebest@gmail.com
    - DOCKER_REPO: richardchien/cqhttp

script:
  - docker build -f Dockerfile -t $DOCKER_REPO:latest .

after_success:
  - chmod +x after_success.sh && ./after_success.sh